DATA_NOT_PROVIDED = "Must provide data."
CREATED = "Data stored successfully."
NOT_FOUND = "File not found."
INVALID_FORMAT = "Invalid data format."
WRONG_LIST_LENGTH = "Exactly two lists must be provided."
STORAGE_DIRECTORY_NAME = "payloads"
